config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root 'ideas#index'
   resources :ideas
   get 'about' => 'static_pages#about'
   get 'random' => 'static_pages#random'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    validates :description, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    def index
        @ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
    end

    def create
        @idea = Idea.create(idea_params)
        if @idea.valid?
          flash[:success] = "Your idea has been posted!"
        else
          flash[:alert] = "Woops! Looks like there has been an error!"
        end
        redirect_to root_path
    end

    def edit
        @idea = Idea.find(params[:id])
    end

    def update
      @idea = Idea.find(params[:id])
      if @idea.update(idea_params)
        flash[:success] = "The idea has been updated!"
        redirect_to root_path
      else
        flash[:alert] = "Woops! Looks like there has been an error!"
        redirect_to edit_idea_path(params[:id])
      end
    end


    def destroy
      @idea = Idea.find(params[:id])
      @idea.destroy
      flash[:success] = "The idea was successfully deleted!"
      redirect_to root_path
    end

    private

    def idea_params
        params.require(:idea).permit(:description, :author)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def about
    end

    def random
        @idea = Idea.order("RANDOM()").first
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<h1>Revise Idea</h1>

<%= simple_form_for @idea, method: :patch do |f| %>
<%= f.input :description %>
  <%= f.input :author %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/ideas/index.html.erb
<div class="text-center">
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
Add Idea
</button>
</div>
<br>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Enter your awesome Idea</h4>
      </div>
        <%= simple_form_for Idea.new do |f| %>
      <div class="modal-body">
          <%= f.input :description %>
          <%= f.input :author %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
        <% end %>
    </div>
  </div>
</div>

<% @ideas.each do |idea| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
        <p><%= idea.description %></p>
        <small>by <%= idea.author %></small>
      </blockquote> 
      <br>
       <div class="btn-group" role="group">
        <%= link_to 'Delete', idea_path(idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
        <%= link_to 'Revise', edit_idea_path(idea), class:'btn btn-sm btn-success' %>
      </div>
    </div>
  </div>
<% end %>
<div class = "text-center">
  <%= will_paginate @ideas %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideator</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Dosis:300,400,600,700|Open+Sans:300,400,600,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div id="wrap">
    <%= render 'shared/nav' %>
    
   <div class = "container">
    <div class = "row">
      <div class = "col-xs-12 col-md-6 col-md-offset-3">
        <%= render 'shared/flash_messages' %>
        <%= yield %>
      </div>
    </div>
  </div>
    <%= render 'shared/footer' %>  
  </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
    <div class="footer text-center">
    <p>Open Sourced on <a href="https://github.com/amitness/ideator">GitHub.</a></p>    
  </div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <!-- <div class="container-fluid"> -->
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="/">Ideator</a>
   </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'All Ideas', root_path %></li>
        <li><%= link_to 'Inspire Me', random_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </div>
</nav>

app/views/static_pages/about.html.erb
<h1>About</h1>

<h4>Share your ideas with the world and find others.</h4>

app/views/static_pages/random.html.erb
<% if @idea.present? %>
  <%= link_to 'Inspire Me', random_path, class: 'btn btn-primary btn-block' %>
    
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
        <p><%= @idea.description %></p>
        <small>by <%= @idea.author %></small>
      </blockquote>
        
      <br>

      <div class="btn-group" role="group">
        <%= link_to 'Delete', idea_path(@idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
        <%= link_to 'Revise', edit_idea_path(@idea), class: 'btn btn-sm btn-success' %>
      </div>
    </div>
  </div>
  <% else %>
  <h4>No ideas have been shared. Add one <%= link_to 'here', root_path %></h4>

<% end %>